---

next: false

---



<BlogInfo id="702"/>

```python
def demo1():
    return int(input("请输入一个整数"))

def demo2():
    return demo1()


try:
    print(demo2())
except Exception as result:
    print("未知错误 %s"%result)
#如果代码出现异常，在函数/方法内部没有对应的异常处理，就会向上传递，直到最后传到主程序
#如果主程序中也没有对应的异常处理，程序就会报错

#在编写代码时，如果碰到到 需要尝试的代码 多次被调用或重写时的情况，可以只在主程序中写
#相应的异常处理，而不需要重复地去写尝试代码，从而减轻了程序员的工作量
```



<ActionBox />
