
<BlogInfo id="526" title="8.并发运行任务" author="白日梦想猿" pv=0 read_times=0 pre_cost_time="0分52秒" category="协程" tag_list="['协程']" create_time="2022.08.13 11:33:44" update_time="2022.08.13 11:50:49" />

```python
# -*- coding: UTF-8 -*-                            
# @Author  ：LLL                         
# @Date    ：2022/8/13 11:33  

import asyncio

'''
asyncio.gather(coros_or_futures,return_exceptions=False)
#并发运行coros_or_futures序列中的协程或者future

#如果所有可等待对象都成功完成，结果将是一个由所有返回值聚合而成的列表。结果值
的顺序与coros_or_futures中可等待对象的苏顺序一致

#return_exceptions默认为False，当可等待对象中的某一个在执行过程中发生异常，
会抛出异常，其他可等待对象继续正常执行，为True时，不会抛出异常，返回的异常会
和正常结果一样处理，添加到返回的列表中

#可等待对象中的某一个终止执行不会影响其他的执行情况

#gather被取消时，所有任务也会被取消

'''

async def sing():
    await asyncio.sleep(1)
    print('两只老虎，两只老虎跑得快...')
    return 'finished sing...'


async def dance():
    await asyncio.sleep(0.5)
    print('大家好，我是练习时长两年半的...')
    return 'finished dance...'


async def drink():
    print('来，再来一杯！')
    return 'finished drink...'


async def eat():
    print('yummy!')
    print(1 / 0)
    return 'finished eat...'


async def main():
    res = await asyncio.gather(
        sing(),
        dance(),
        drink(),
        eat(),
        return_exceptions=True
    )
    print(res)


asyncio.run(main())

```
