---
sidebar: false
next: false
---
<BlogInfo/>






```python
# -*- coding: UTF-8 -*-
'''
   *****************LLL*********************
   * @Project ：16.协程                       
   * @File    ：lll04_让协程返回值.py                  
   * @IDE     ：PyCharm             
   * @Author  ：LLL                         
   * @Date    ：2022/4/27 9:14             
   *****************************************
'''
def averager():
    total = 0
    count = 0
    average = 0
    while True:
        term = yield average  # send()的值会传给term
        if not term:
            break
        total += term
        count += 1
        average = total / count
        print(average)

    return (total, count, average)


if __name__ == '__main__':
    my_avg = averager()
    print(next(my_avg))  # 激活协程 可以看到协程产出的初始值是average的初始值为None

    my_avg.send(1)
    my_avg.send(2)
    try:  # 发送None，导致协程结束，返回结果，一如既往，生成器对象会抛出StopIteration异常
        # 异常对象的value属性保存着返回的值
        my_avg.send(None)
    except StopIteration as res:
        print(res.value)






```






<ActionBox />
        
<style>#top-box {margin-top:0.5rem!important;}</style>